{
 "title": "Uptime Robot Dashboard",
 "panels": [
  {
   "title": "Number of sites (monitors)",
   "type": "singlestat",
   "description": "Number of monitors on uptimerobot",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "count(uptimerobot_monitor_up) " }
   ]
  },
  {
   "title": "Sites UP",
   "type": "singlestat",
   "description": "Number of monitors up",
   "gridPos": { "h": 2, "w": 6, "x": 6, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(uptimerobot_monitor_status == 2)"
    }
   ]
  },
  {
   "title": "Sites down",
   "type": "singlestat",
   "description": "Number of monitors with status 'seems down' (8) or 'down' (9)",
   "gridPos": { "h": 2, "w": 6, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(uptimerobot_monitor_status > 2) "
    }
   ]
  },
  {
   "title": "Sites paused or not checked yet",
   "type": "singlestat",
   "description": "Number of monitors with status 'paused' (0) or 'not checked yet'  (1)",
   "gridPos": { "h": 2, "w": 6, "x": 18, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(uptimerobot_monitor_status <= 1) "
    }
   ]
  },
  {
   "title": "Response time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 2 },
   "yaxes": [
    { "format": "ms", "label": "Response Time" }
   ],
   "targets": [
    {
     "expr": "uptimerobot_monitor_responsetime",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Site uptime",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "avg(uptimerobot_monitor_up) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "SSL Expiration",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "uptimerobot_monitor_ssl - time()",
     "legendFormat": "{{name}}"
    }
   ]
  }
 ]
}